version: '3'
services:
  swagger-ui:
    build: ./containers/swagger-ui
    environment:
      API_URL: swagger.yaml
    ports:
      - "50000:8080"
    links:
      - swagger-editor
    depends_on:
      - swagger-editor
    volumes:
      - "${DEV_ROOT}/swagger/swagger.yaml:/usr/share/nginx/html/swagger.yaml"

  swagger-editor:
    build: ./containers/swagger-editor
    ports:
      - "50001:8080"
